clippy_task:
    matrix:
        - env:
              RUST_FEATURES: ""
        - env:
              RUST_FEATURES: "--features github"
        - env:
              RUST_FEATURES: "--features gitlab"
        - env:
              RUST_FEATURES: "--features forgejo"
        - env:
              RUST_FEATURES: "--all-features"
    container:
        image: rust:latest
    component_script: rustup component add clippy
    toolchain_cache:
        folder: $RUSTUP_HOME
        fingerprint_script: rustc --version
    cargo_cache:
        folder: $CARGO_HOME/registry
        fingerprint_script: cat Cargo.lock
    clippy_script: cargo clippy $RUST_FEATURES

rustfmt_task:
    container:
        image: rustlang/rust:nightly
    component_script: rustup component add rustfmt
    fmt_script: cargo fmt --all -- --check

linux_task:
    container:
        image: rust:latest
    matrix:
        - env:
              RUSTVER: stable
              RUST_FEATURES: --all-features
        - env:
              RUSTVER: stable
              RUST_FEATURES: ""
        - allow_failures: true
          env:
              RUSTVER: nightly
              RUST_FEATURES: --all-features
    rustup_script: rustup toolchain install $RUSTVER
    toolchain_cache:
        folder: $RUSTUP_HOME
        fingerprint_script: rustc +$RUSTVER --version
    cargo_cache:
        folder: $CARGO_HOME/registry
        fingerprint_script: cat Cargo.lock
    build_script: cargo +$RUSTVER build $RUST_FEATURES
    test_script: cargo +$RUSTVER test $RUST_FEATURES
    before_cache_script: rm -rf $CARGO_HOME/registry/index
